[project]
name = "hospital-agent-github-ready"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain>=1.4.2",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.12",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]
